### ISSUE TITLE
Compile Tailwind to minified CSS

### ISSUE THREAD

**Issue by brainwo** [ClementBeal/maurice#2]
Tailwind Play CDN (https://cdn.tailwindcss.com) is huge. It's 365.68 kB download size and is only designed for development purposes[1]. Compiled Tailwind will be less than 10 kB[2].

---

References:
[1] https://tailwindcss.com/docs/installation/play-cdn
> Use the Play CDN to try Tailwind right in the browser without any build step. The Play CDN is designed for development purposes only, and is not the best choice for production.

[2] My compiled Tailwind CSS (2.56 kB): https://brainwo.github.io/hacktubernews/style.css

**Comment by ClementBeal** [comment]
Thank you for the issue!

I have removed Tailwind from the Maurice base template and instead, the example has a compiled version of it now.
